"""Parse the source .docx into a structured model: sections -> entries -> blocks.

Nothing is rewritten: only whitespace is collapsed and hand-typed list markers
(א. / 1) / א': ...) are lifted off the front of paragraphs so they can be
re-generated by the new design.
"""
import re, json
from xml.etree import ElementTree as ET

NS = {'w': 'http://schemas.openxmlformats.org/wordprocessingml/2006/main'}
W = '{%s}' % NS['w']

# ----------------------------------------------------------------- reading
def _on(rp, tag):
    if rp is None: return False
    e = rp.find('w:' + tag, NS)
    return e is not None and e.get(W + 'val') not in ('0', 'false', 'none')

def read_paragraphs(path):
    root = ET.parse(path).getroot()
    out = []
    for idx, p in enumerate(root.find('w:body', NS).findall('w:p', NS)):
        chars = []   # (char, b, i, u)
        for r in p.iter(W + 'r'):
            rp = r.find('w:rPr', NS)
            b, i, u = _on(rp, 'b'), _on(rp, 'i'), _on(rp, 'u')
            for t in r.findall('w:t', NS):
                for ch in (t.text or ''):
                    chars.append((ch, b, i, u))
        ppr = p.find('w:pPr', NS)
        num = None
        if ppr is not None and ppr.find('w:numPr', NS) is not None:
            n = ppr.find('w:numPr', NS)
            num = (n.find('w:numId', NS).get(W + 'val'), n.find('w:ilvl', NS).get(W + 'val'))
        out.append(Para(idx, chars, num))
    return out

class Para:
    def __init__(self, idx, chars, num):
        self.idx, self.num = idx, num
        # collapse whitespace (keeps format of the first space of a run of spaces)
        res = []
        for c in chars:
            ch = 'WS' if (c[0].isspace() or c[0] in '‏‎') else c[0]
            if ch == 'WS':
                if res and res[-1][0] == ' ': continue
                res.append((' ', c[1], c[2], c[3]))
            else:
                res.append(c)
        while res and res[0][0] == ' ': res.pop(0)
        while res and res[-1][0] == ' ': res.pop()
        self.chars = res
    @property
    def text(self): return ''.join(c[0] for c in self.chars)
    @property
    def blank(self): return not self.chars
    def frac(self, k):          # share of non-space chars with b/i/u
        ns = [c for c in self.chars if c[0] != ' ']
        if not ns: return 0.0
        return sum(1 for c in ns if c[k]) / len(ns)
    @property
    def bold(self): return self.frac(1)
    @property
    def italic(self): return self.frac(2)
    def runs(self, strip=0, emph_bold=True, lo=None, hi=None):
        """list of (text, {'e':bool,'u':bool}); bold counts as emphasis only if the paragraph is not (almost) all bold"""
        ch = self.chars[(lo or 0):(hi if hi is not None else len(self.chars))]
        ch = ch[strip:]
        while ch and ch[0][0] == ' ': ch = ch[1:]
        allbold = self.bold > 0.85
        out = []
        for c, b, i, u in ch:
            f = (bool(b and emph_bold and not allbold), bool(u))
            if out and out[-1][1] == f: out[-1][0] += c
            else: out.append([c, f])
        return [(t, {'e': f[0], 'u': f[1]}) for t, f in out]

# ----------------------------------------------------------------- helpers
GER = {1:'א',2:'ב',3:'ג',4:'ד',5:'ה',6:'ו',7:'ז',8:'ח',9:'ט',10:'י',20:'כ',30:'ל',40:'מ',50:'נ',60:'ס',70:'ע',80:'פ',90:'צ',
       100:'ק',200:'ר',300:'ש',400:'ת'}
def heb_num(n):
    """1->א ... 15->טו 16->טז 22->כב (no punctuation, as in the example)"""
    if n == 15: return 'טו'
    if n == 16: return 'טז'
    s = ''
    for v in sorted(GER, reverse=True):
        while n >= v:
            s += GER[v]; n -= v
    return s

HEB_LETTER = r'[א-ת]{1,2}'
def marker_prefix_len(p, kind):
    """length (in chars of p.chars) of a typed list marker at the start, 0 if none"""
    t = p.text
    pats = {
        'dot':   r'^(' + HEB_LETTER + r')\s*[\.\)]\s*',          # א.   ט.   ד)
        'num':   r'^(\d{1,2})\s*\)\s*',                          # 1)  5)
        'geresh': r'^(' + HEB_LETTER + r")'\s*:?\s*",           # א':
        'bare':  r'^(' + HEB_LETTER + r')\s+(?=\S)',             # "א למה"   (only used where the marker is a bold run)
        'bare!': r'^(' + HEB_LETTER + r')\s+(?=\S)',            # same, bold not required
    }
    m = re.match(pats[kind], t)
    if not m: return 0
    if kind == 'bare':
        # must be a bold lone token
        n = len(m.group(1))
        if not all(c[1] for c in p.chars[:n]): return 0
    if kind == 'bare!': kind = 'bare'
    return m.end()

def blk(kind, p, **kw):
    """block from paragraph p; kind in q (question text), name, src, label"""
    return dict(kind=kind, runs=p.runs(**kw), idx=p.idx)

def strip_runs(p, kind, kindname='q'):
    n = marker_prefix_len(p, kind)
    return dict(kind=kindname, runs=p.runs(strip=n), idx=p.idx)

def name_blk(p, strip=0):
    runs = p.runs(strip=strip)
    if runs and runs[-1][0].endswith('.'): runs[-1] = (runs[-1][0][:-1], runs[-1][1])
    return dict(kind='name', runs=runs, idx=p.idx)

def norm_siman(s):
    s = s.strip().rstrip('.').strip()
    return s.replace("'", '').replace('"', '').replace('״', '').replace('׳', '')

# ----------------------------------------------------------------- the model
def build(path='input_document.xml'):
    P = read_paragraphs(path)
    R = lambda *r: [P[i] for i in r]
    rng = lambda a, b: [P[i] for i in range(a, b + 1) if not P[i].blank]
    sections = []
    def S(num=None, title=None, sub=None):
        s = dict(num=num, title=title, entries=[])
        if sub: s['entries'].append(dict(type='caption', runs=[(sub, {})], idx=-1))
        sections.append(s); return s
    def item(sec, blocks): sec['entries'].append(dict(type='item', blocks=blocks))
    def caption(sec, text): sec['entries'].append(dict(type='caption', runs=[(text, {})], idx=-1))

    def numbered_items(sec, a, b):
        for p in rng(a, b):
            if p.num: item(sec, [blk('q', p)])

    # ---- סימן ד
    s = S('ד', sub='הלכות נטילת ידים'); numbered_items(s, 2, 30)
    # ---- סימן ה
    s = S('ה', sub="כוונת שם ה'"); numbered_items(s, 34, 52)
    item(s, [blk('q', P[56]), blk('q', P[57]), blk('q', P[58]), name_blk(P[55])])
    for i in (61, 62, 63, 65): item(s, [strip_runs(P[i], 'geresh'), name_blk(P[60])])
    item(s, [blk('q', P[68]), name_blk(P[67])])
    # ---- סימן ו
    s = S('ו', sub='ברכת אשר יצר'); numbered_items(s, 72, 78)
    # ---- סימן ח סעיף יד
    s = S('ח'); caption(s, 'סעיף יד')
    item(s, [strip_runs(P[81], 'num')] + [blk('q', P[i]) for i in (82, 83, 84, 85)])
    item(s, [strip_runs(P[86], 'num')])
    item(s, [strip_runs(P[88], 'num')] + [blk('q', P[i]) for i in (89, 90)])
    item(s, [strip_runs(P[91], 'num')])
    item(s, [strip_runs(P[92], 'num')])
    item(s, [strip_runs(P[93], 'num'), blk('q', P[94])])
    caption(s, 'שאלה הלכה למעשה')
    item(s, [strip_runs(P[96], 'num'), blk('q', P[97])])
    # ---- סימן יח / כא
    s = S('יח'); item(s, [blk('q', P[101]), blk('q', P[102]), name_blk(P[100])])
    s = S('כא'); item(s, [blk('q', P[106]), name_blk(P[105])]); item(s, [blk('q', P[107]), name_blk(P[105])])
    # ---- סימן מז
    s = S('מז')
    item(s, [strip_runs(P[110], 'dot')] + [blk('q', P[i]) for i in (111, 112)])
    item(s, [strip_runs(P[114], 'dot')] + [blk('q', P[i]) for i in (115, 116, 117, 118)])
    item(s, [strip_runs(P[120], 'dot')] + [blk('q', P[i]) for i in (121, 122)])
    item(s, [strip_runs(P[124], 'dot'), blk('q', P[125])])
    for i in (126, 127, 128, 129): item(s, [strip_runs(P[i], 'dot')])
    item(s, [strip_runs(P[131], 'dot'), blk('q', P[132]), blk('q', P[133])])
    for i in (134, 135, 136, 137): item(s, [strip_runs(P[i], 'dot')])
    # ---- סימנים עם שמות הרבנים אחרי כל שאלה (מח – נג)
    def qn(sec, q_idx, n_idx, extra=()):
        blocks = [strip_runs(P[q_idx], 'bare'), name_blk(P[n_idx])]
        for (kq, kn) in extra: blocks += [strip_runs(P[kq], 'bare'), name_blk(P[kn])]
        item(sec, blocks)
    def ans(sec_item_blocks, a_idx, n_idx):
        sec_item_blocks += [blk('q', P[a_idx]), name_blk(P[n_idx])]
    s = S('מח'); qn(s, 141, 142); qn(s, 144, 145)
    s = S('מט'); qn(s, 148, 149); qn(s, 151, 152)
    s = S('נא'); qn(s, 155, 156); qn(s, 157, 158); qn(s, 159, 160)
    s = S('נב'); qn(s, 162, 163); qn(s, 164, 165); qn(s, 166, 167)
    s = S('נג')
    qn(s, 170, 171, extra=[]); s['entries'][-1]['blocks'] += [blk('q', P[172]), name_blk(P[173])]
    qn(s, 174, 175); qn(s, 176, 177)
    qn(s, 178, 179); s['entries'][-1]['blocks'] += [blk('q', P[180]), name_blk(P[181])]
    item(s, [blk('q', P[182]), name_blk(P[183]), blk('q', P[184]), name_blk(P[185])])
    qn(s, 186, 187); s['entries'][-1]['blocks'] += [blk('q', P[188]), name_blk(P[189])]
    for q, n in ((190, 191), (192, 193), (194, 195), (196, 197), (198, 199), (200, 201), (202, 203), (204, 205), (206, 207), (208, 209)):
        qn(s, q, n)
    # ---- סימנים סג – סה
    s = S('סג'); item(s, [blk('q', P[213])])
    item(s, [blk('q', P[i]) for i in (216, 217, 218)])
    item(s, [blk('q', P[i]) for i in (219, 220, 221, 222, 223, 224)])
    s = S('סד'); item(s, [blk('q', P[i]) for i in (227, 228, 229, 230)])
    s = S('סה')
    for i in (233, 234, 235, 236, 237): item(s, [strip_runs(P[i], 'num')])
    # ---- סימן עא
    s = S('עא')
    item(s, [strip_runs(P[240], 'bare')]); item(s, [strip_runs(P[241], 'bare')]); item(s, [strip_runs(P[242], 'bare!')])
    item(s, [strip_runs(P[243], 'dot')])
    item(s, [strip_runs(P[244], 'dot'), blk('q', P[245]), blk('q', P[246])])
    item(s, [strip_runs(P[247], 'dot')] + [blk('q', P[i]) for i in (248, 249, 250, 251)])
    item(s, [strip_runs(P[252], 'dot')]); item(s, [strip_runs(P[253], 'dot')])
    item(s, [blk('src', P[255])] + [blk('q', P[i]) for i in (256, 257, 258)] + [name_blk(P[254], marker_prefix_len(P[254], 'dot'))])
    item(s, [blk('q', P[i]) for i in (262, 263, 264, 265, 266)] + [name_blk(P[260], marker_prefix_len(P[260], 'dot'))])
    item(s, [blk('src', P[268])] + [blk('q', P[i]) for i in (269, 270, 271, 272)] + [name_blk(P[267], marker_prefix_len(P[267], 'dot'))])
    # ---- סימן קכג  (the numbered paragraphs are the answers/points; kept as sub-points)
    s = S('קכג')
    item(s, [blk('q', P[275])] + [dict(kind='sub', label=heb_num(k + 1), runs=P[i].runs(), idx=i) for k, i in enumerate(range(276, 282))])
    # ---- סימן רטו
    s = S('רטו')
    for q, n in ((284, 285), (287, 288), (290, 291), (293, 294)): qn(s, q, n)
    # ---- שאלות שונות בעניני תפילה
    s = S(title='שאלות שונות בעניני תפילה')
    for i in (298, 300, 302, 304, 306, 308): item(s, [blk('q', P[i])])
    # ---- בין הזמנים
    s = S(title='שאלה להלכה למעשה – בין הזמנים')
    item(s, [blk('q', P[i]) for i in (312, 313, 314)] +
            [dict(kind='sub', label=heb_num(k + 1), runs=P[i].runs(), idx=i) for k, i in enumerate(range(315, 323))])
    # ---- שאלות לעיונא (practical halacha) ------------------------------------
    s = S(title='שאלות לעיונא')
    cur = None
    cur_item = None
    def parse_ref(text):
        m = re.match(r'^סימן\s+(\S+?)\.?(?:\s+(.*))?$', text)
        siman = norm_siman(m.group(1))
        rest = (m.group(2) or '').strip()
        rest = re.sub(r'\.\s*(?=[–=-])', ' ', rest).strip().rstrip('.').strip()
        rest = re.sub(r'^(\S+ \S+)\.\s+(?![–=-])(\S)', r'\1 – \2', rest)
        return siman, rest
    for p in rng(331, len(P) - 1):
        t = p.text
        if re.match(r'^סימן\s', t) and len(t) < 70 and p.bold < 0.5 and 'הלכה' not in t:
            siman, rest = parse_ref(t)
            if cur != siman:
                sections.append(dict(num=siman, title=None, entries=[])); cur = siman
            if rest: caption(sections[-1], rest)
            cur_item = None
            continue
        sec = sections[-1]
        # split a paragraph into its bold-italic head and non-bold tail
        n = len(p.chars)
        cut = n
        for k, c in enumerate(p.chars):
            if not c[1] and c[0] != ' ':
                cut = k; break
        if t.startswith('הלכה'):
            head = dict(kind='q', runs=p.runs(lo=0, hi=cut, emph_bold=False), idx=p.idx)
            # label + question split over several bold runs (527, 763) are all bold so cut==n
            blocks = [head]
            if cut < n:
                tail = p.runs(lo=cut, emph_bold=False)
                if ''.join(x[0] for x in tail).strip():
                    # tail may contain more bold text (527/763: "label | spaces | question") -> handled by cut logic: first non-bold char is a space only
                    blocks.append(dict(kind='src', runs=tail, idx=p.idx))
            item(sec, blocks); cur_item = sec['entries'][-1]
        else:
            # source line (italic) -> attaches to the item before it
            runs = p.runs(emph_bold=False)
            if cur_item is None or sec['entries'][-1] is not cur_item:
                item(sec, [dict(kind='src', runs=runs, idx=p.idx)]); cur_item = sec['entries'][-1]
            else:
                cur_item['blocks'].append(dict(kind='src', runs=runs, idx=p.idx))
    # merge consecutive sections with the same siman (the source repeats headings)
    merged = []
    for sec in sections:
        if merged and sec['num'] and merged[-1]['num'] == sec['num']:
            merged[-1]['entries'] += sec['entries']
        else: merged.append(sec)
    return merged

if __name__ == '__main__':
    import sys
    m = build()
    json.dump(m, open('model.json', 'w'), ensure_ascii=False, indent=1)
    letters = 0
    for sec in m:
        print('=== ' + (('סימן ' + sec['num']) if sec['num'] else sec['title']))
        k = 0
        for e in sec['entries']:
            if e['type'] == 'caption': print('   (caption)', ''.join(r[0] for r in e['runs'])); continue
            k += 1
            first = e['blocks'][0]
            txt = ''.join(r[0] for r in first['runs'])
            print('   %2d [%s] %s … (%d blocks)' % (k, heb_num(k), txt[:70], len(e['blocks'])))
